src/AppBundle/Entity/Media/Image.php
<?php

namespace AppBundle\Entity\Media;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Groups;

/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\Media\ImageRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $idImage;

    /**
     * @var \AppBundle\Entity\Work\Intervention
     *
     * @ORM\ManyToOne(targetEntity="\AppBundle\Entity\Work\Intervention", inversedBy="images")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="intervention", referencedColumnName="id", nullable=false)
     * })
     * @Groups({"details_image"})
     */
    private $intervention;

    /**
     * @var string
     *
     * @ORM\Column(name="nom_fichier", type="string", length=255)
     * @Groups({"list_image", "details_image"})
     */
    private $nomFichier;

    /**
     * @var string
     *
     * @ORM\Column(name="repertoire", type="string", length=255)
     * @Groups({"list_image", "details_image"})
     */
    private $repertoire;

    /**
     * Fichier de l'image
     *
     * @var \Symfony\Component\HttpFoundation\File\UploadedFile
     * @Assert\Image(maxSize = "2048k")
     */
    private $file;


    /**
     * Get id
     *
     * @return integer
     */
    public function getIdImage()
    {
        return $this->idImage;
    }

    /**
     * Set nomFichier
     *
     * @param string $nomFichier
     * @return Image
     */
    public function setNomFichier($nomFichier)
    {
        $this->nomFichier = $nomFichier;

        return $this;
    }

    /**
     * Get nomFichier
     *
     * @return string
     */
    public function getNomFichier()
    {
        return $this->nomFichier;
    }

    /**
     * Set repertoire
     *
     * @param string $repertoire
     * @return Image
     */
    public function setRepertoire($repertoire)
    {
        $this->repertoire = $repertoire;

        return $this;
    }

    /**
     * Get repertoire
     *
     * @return string
     */
    public function getRepertoire()
    {
        return $this->repertoire;
    }

    /**
     * Set intervention
     *
     * @param \AppBundle\Entity\Work\Intervention $intervention
     * @return Image
     */
    public function setIntervention(\AppBundle\Entity\Work\Intervention $intervention)
    {
        $this->intervention = $intervention;

        return $this;
    }

    /**
     * Get intervention
     *
     * @return \AppBundle\Entity\Work\Intervention
     */
    public function getIntervention()
    {
        return $this->intervention;
    }

    /**
     * Sets file.
     *
     * @param \Symfony\Component\HttpFoundation\File\UploadedFile $file
     * @return Image
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = null)
    {
        $this->file = $file;
        $this->nomFichier = null;

        return $this;
    }

    /**
     * Get file.
     *
     * @return \Symfony\Component\HttpFoundation\File\UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Renvoie le chemin absolu sur le serveur jusqu'au fichier uploadé
     *
     * @return null|string
     */
    public function getAbsolutePath()
    {
        return $this->nomFichier === null
            ? null
            : $this->getUploadRootDir().'/'.$this->repertoire.'/'.$this->nomFichier;
    }

    /**
     * Renvoie le chemin relatif jusqu'au fichier uploadé, chemin utilisé sur les pages web
     *
     * @return null|string
     */
    public function getWebPath()
    {
        return $this->nomFichier === null
            ? null
            : $this->getUploadDir().'/'.$this->repertoire.'/'.$this->nomFichier;
    }

    /**
     * Renvoie le chemin jusqu'au répertoire des uploads sur le serveur
     *
     * @return string
     */
    private function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    /**
     * Renvoie le répertoire précis où sont uploadées les images dans le répertoire des uploads sur le serveur
     *
     * @return string
     * @Groups({"list_image", "details_image"})
     */
    private function getUploadDir()
    {
        return 'uploads/images';
    }

    /**
     * Instructions exécutées avant enregistrement des infos de l'image dans la base de données
     *
     * @ORM\PrePersist()
     */
    public function preUpload()
    {
        // Définition du répertoire du fichier
        $this->repertoire = 'Operation'.$this->intervention->getOperation()->getIdOperation();

        if (null !== $this->getFile()) {
            // Génération d'un nom de fichier unique
            $filename = md5($this->idImage);
            // Ajout de l'extension au nom de fichier généré
            $this->nomFichier = $filename.'.'.$this->getFile()->guessExtension();
        }
    }

    /**
     * Instructions exécutées après enregistrement des infos de l'image dans la base de données
     *
     * @ORM\PostPersist()
     */
    public function postUpload()
    {
        if (null === $this->getFile()) {
            return;
        }

        // Déplacement du fichier dans le répertoire des uploads.
        // Une erreur est déchenchée automatiquement en cas d'erreur et l'enregistrement des infos de l'images est annulé
        $this->getFile()->move($this->getUploadRootDir().'/'.$this->repertoire, $this->nomFichier);

        $this->file = null;
    }

    /**
     * Supression de l'image après suppresion de son occurence.
     *
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        $file = $this->getAbsolutePath();
        if ($file) {
            unlink($file);
        }
    }

}

src/AppBundle/Form/Work/InterventionType.php
<?php

namespace AppBundle\Form\Work;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InterventionType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dateIntervention', 'Symfony\Component\Form\Extension\Core\Type\DateType', array(
                'widget' => ('single_text'),
                'format' => 'd/M/y',
                'html5' => false,
                'read_only' => true,
                'attr' => array(
                    'class' => 'date'
                )
            ))
            ->add('notes')
            ->add('images', 'Symfony\Component\Form\Extension\Core\Type\CollectionType', array(
                'entry_type' => 'AppBundle\Form\Media\ImageType',
                'allow_add' => true,
                'delete_empty' => true,
                'by_reference' => false,
                'entry_options' => array(
                    'label' => false,
                )
            ))
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Work\Intervention'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_intervention';
    }


}

src/AppBundle/Form/Work/OperationEditType.php
<?php

namespace AppBundle\Form\Work;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OperationEditType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dateFinEffective', 'Symfony\Component\Form\Extension\Core\Type\DateType', array(
                'widget' => ('single_text'),
                'format' => 'd/M/y',
                'html5' => false,
                'read_only' => true,
                'attr' => array(
                    'class' => 'date'
                )
            ))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Work\Operation'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_operation_edit';
    }


}

src/AppBundle/Form/Work/OperationType.php
<?php

namespace AppBundle\Form\Work;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OperationType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('sujet')
            ->add('description')
            ->add('dateDebut', 'Symfony\Component\Form\Extension\Core\Type\DateType', array(
                'widget' => ('single_text'),
                'format' => 'd/M/y',
                'html5' => false,
                'read_only' => true,
                'attr' => array(
                    'class' => 'date'
                )
            ))
            ->add('dateFinPrevue', 'Symfony\Component\Form\Extension\Core\Type\DateType', array(
                'widget' => ('single_text'),
                'format' => 'd/M/y',
                'html5' => false,
                'read_only' => true,
                'attr' => array(
                    'class' => 'date'
                )
            ))
            ->add('pieces', 'Symfony\Component\Form\Extension\Core\Type\CollectionType', array(
                'entry_type' => 'AppBundle\Form\Work\PieceType',
                'allow_add' => true,
                'delete_empty' => true,
                'by_reference' => false,
            ))
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Work\Operation'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_operation';
    }


}

src/AppBundle/Form/Work/PieceType.php
<?php

namespace AppBundle\Form\Work;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PieceType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('description')
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Work\Piece'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_piece';
    }


}

src/AppBundle/Controller/Work/InterventionController.php
<?php

namespace AppBundle\Controller\Work;

use AppBundle\Entity\Work\Intervention;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * Controller pour les interventions.
 *
 * @Route("interventions")
 * @Security("has_role('ROLE_MANAGER') or has_role('ROLE_TECHNICIAN')")
 */
class InterventionController extends Controller
{
    /**
     * Affiche une intervention d'une opération.
     *
     * @Route("/{idIntervention}", name="interventions_show")
     * @Method("GET")
     * @param Intervention $intervention
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showAction(Intervention $intervention)
    {
        return $this->render('AppBundle:Work/Intervention:show.html.twig', array(
            'intervention' => $intervention,
        ));
    }
}

src/AppBundle/Controller/Work/OperationController.php
<?php

namespace AppBundle\Controller\Work;

use AppBundle\Entity\Work\Intervention;
use AppBundle\Entity\Work\Operation;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;

/**
 * Controller pour les opérations.
 * 
 * @Route("/operations")
 * @Security("has_role('ROLE_MANAGER') or has_role('ROLE_TECHNICIAN')")
 */
class OperationController extends Controller
{
    /**
     * Affiche une opération d'un véhicule.
     *
     * @Route("/{idOperation}", name="operations_show")
     * @Method("GET")
     * @param Operation $operation
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showAction(Operation $operation)
    {
        return $this->render('AppBundle:Work/Operation:show.html.twig', array(
            'operation' => $operation,
        ));
    }

    /**
     * Displays a form to edit an existing operation entity.
     *
     * @Route("/{idOperation}/edit", name="operations_edit")
     * @Method({"GET", "POST"})
     * @Security("has_role('ROLE_TECHNICIAN')")
     */
    public function editAction(Request $request, Operation $operation)
    {
        $editForm = $this->createForm('AppBundle\Form\Work\OperationEditType', $operation);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('operations_show', array('idOperation' => $operation->getIdOperation()));
        }

        return $this->render('AppBundle:Work/Operation:edit.html.twig', array(
            'operation' => $operation,
            'edit_form' => $editForm->createView(),
        ));
    }

    /**
     * Liste toutes les interventions de l'opération passée en paramètre.
     *
     * @Route("/{idOperation}/interventions", name="interventions_index")
     * @Method("GET")
     * @param Operation $operation
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(Operation $operation)
    {
        $em = $this->getDoctrine()->getManager();

        $interventions = $em->getRepository('AppBundle:Work\Intervention')->findBy(array(
            'operation' => $operation,
        ));

        return $this->render('AppBundle:Work/Intervention:index.html.twig', array(
            'interventions' => $interventions,
            'operation' => $operation,
        ));
    }

    /**
     * Crée une intervention d'une opération.
     *
     * @Route("{idOperation}/interventions/new", name="interventions_new")
     * @Method({"GET", "POST"})
     * @Security("has_role('ROLE_TECHNICIAN')")
     */
    public function newAction(Request $request, Operation $operation)
    {
        $intervention = new Intervention();
        // Enregistrement du créateur
        $intervention->setCreateur($this->getUser());

        // Enregistrement de l'opération concernée
        $intervention->setOperation($operation);

        $form = $this->createForm('AppBundle\Form\Work\InterventionType', $intervention);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($intervention);
            $em->flush();

            return $this->redirectToRoute('interventions_show', array('idIntervention' => $intervention->getIdIntervention()));
        }

        return $this->render('@App/Work/Intervention/new.html.twig', array(
            'intervention' => $intervention,
            'form' => $form->createView(),
        ));
    }
}

src/AppBundle/Controller/Work/ProblemeController.php
<?php

namespace AppBundle\Controller\Work;

use AppBundle\Entity\Work\Probleme;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;

/**
 * Controller pour les problèmes.
 *
 * @Route("problems")
 * @Security("has_role('ROLE_MANAGER') or has_role('ROLE_TECHNICIAN')")
 */
class ProblemeController extends Controller
{
    /**
     * Affiche un problème.
     *
     * @Route("/{idProbleme}", name="problems_show")
     * @Method("GET")
     * @param Probleme $probleme
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showAction(Probleme $probleme)
    {
        return $this->render('AppBundle:Work/Probleme:show.html.twig', array(
            'probleme' => $probleme,
        ));
    }
}

src/AppBundle/Resources/views/Work/Intervention/index.html.twig
{% extends 'AppBundle:Default:index.html.twig' %}

{% block title %}Interventions{% endblock %}

{% block page %}
    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">Interventions de operation</h1>
            <div class="row">
                <div class=col-sm-2>
                    <h4 class="sub-header"><a href="{{ path('cars_show', { 'idVehicule': operation.vehiculeConcerne.idVehicule }) }}">Vehicule concerné</a></h4>
                    <h5>Immatriculation : {{ operation.VehiculeConcerne.immatriculation }}</h5>
                    <h5>Marque : {{ operation.VehiculeConcerne.marque }}</h5>
                    <h5>Modele : {{ operation.VehiculeConcerne.modele }}</h5>
                    <h5>Type : {{ operation.VehiculeConcerne.type }}</h5>
                    <h5>Date achat : {{ operation.VehiculeConcerne.dateAchat|date('d/m/Y') }}</h5>
                </div>
                
                <div class=col-sm-3>
                    <h4 class="sub-header"><a href="{{ path('operations_show', { 'idOperation': operation.idOperation }) }}">Operation concernée</a></h4>
                    <h5>Sujet : {{ operation.sujet }}</h5>
                    <h5>Description : {{ operation.description }}</h5>
                    <h5>Date debut : {{ operation.dateDebut|date('d/m/Y') }}</h5>
                    <h5>Date fin prevue : {{ operation.dateFinPrevue|date('d/m/Y') }}</h5>
                    <h5>Date fin effective : {% if operation.dateFinEffective %}{{ operation.dateFinEffective|date('d/m/Y') }}{% endif %}</h5>
                </div>
                
                <div class="col-sm-7">
                    <h2 class="sub-header">Interventions</h2>
                    <h3 class="sub-header"><a href="{{ path('interventions_new', { 'idOperation': operation.idOperation }) }}">Créer une nouvelle intervention pour cette operation</a></h3>
                
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>Date intervention</th>
                                <th>Intervenant</th>
                                <th>Notes</th>
                                <th>Date et heure creation</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for intervention in interventions %}
                                    <tr>
                                        <td>{{ intervention.dateIntervention|date('d/m/Y') }}</td>
                                        <td>{{ intervention.createur.prenom ~ ' ' ~ intervention.createur.nom }}</td>
                                        <td>{{ intervention.notes }}</td>
                                        <td>{{ intervention.createdAt|date('d/m/Y H:i') }}</td>
                                        <td>
                                            <div class="btn-group btn-group-xs" role="group">
                                                <a type="button" class="btn btn-primary" href="{{ path('interventions_show', { 'idIntervention': intervention.idIntervention }) }}"><span class="glyphicon glyphicon-eye-open"></span> Détails</a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Work/Intervention/layout.html.twig
{% extends 'AppBundle:Default:index.html.twig' %}

{% block page %}
    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">Interventions de operation</h1>
            <div class="row">
                <div class=col-sm-2>
                    <h4 class="sub-header"><a href="{{ path('cars_show', { 'idVehicule': intervention.operation.vehiculeConcerne.idVehicule }) }}">Vehicule concerné</a></h4>
                    <h5>Immatriculation : {{ intervention.operation.VehiculeConcerne.immatriculation }}</h5>
                    <h5>Marque : {{ intervention.operation.VehiculeConcerne.marque }}</h5>
                    <h5>Modele : {{ intervention.operation.VehiculeConcerne.modele }}</h5>
                    <h5>Type : {{ intervention.operation.VehiculeConcerne.type }}</h5>
                    <h5>Date achat : {{ intervention.operation.VehiculeConcerne.dateAchat|date('d/m/Y') }}</h5>
                </div>
                
                <div class=col-sm-3>
                    <h4 class="sub-header"><a href="{{ path('operations_show', { 'idOperation': intervention.operation.idOperation }) }}">Operation concernée</a></h4>
                    <h5>Sujet : {{ intervention.operation.sujet }}</h5>
                    <h5>Description : {{ intervention.operation.description }}</h5>
                    <h5>Date debut : {{ intervention.operation.dateDebut|date('d/m/Y') }}</h5>
                    <h5>Date fin prevue : {{ intervention.operation.dateFinPrevue|date('d/m/Y') }}</h5>
                    <h5>Date fin effective : {% if intervention.operation.dateFinEffective %}{{ intervention.operation.dateFinEffective|date('d/m/Y') }}{% endif %}</h5>
                </div>
                
                {% block content %}
                {% endblock %} 
                
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Work/Intervention/new.html.twig
{% extends 'AppBundle:Work/Intervention:layout.html.twig' %}

{% block title %}Intervention creation{% endblock %}

{% block content %}
    <div class="col-sm-7">
        <h2 class="sub-header">Intervention creation</h2>
        
        <div class="row">
            <div class="col-sm-12">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <a href="#" id="add_image" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Ajouter une image"><i class="glyphicon glyphicon-plus"></i></a>
                <input type="submit" class="btn btn-primary btn-block" value="Valider" />
                {{ form_end(form) }}
            </div>
        </div>
        
        <h3 class="sub-header"><a href="{{ path('interventions_index', { 'idOperation': intervention.operation.idOperation }) }}">Retour à la liste</a></h3>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function() {
            var $container = $('div#app_intervention_images');
            var index = $container.children('div.row').length;
            $('#add_image').click(function(e) {
                addImage($container);
                e.preventDefault();
                return false;
            });

            function addImage($container) {
                var template = $container.attr('data-prototype')
                                .replace(/__name__label__/g, 'Image ' + (index+1))
                                .replace(/__name__/g,        index)
                        ;
                var $prototype = $(template);
                $container.append($prototype);
                index++;
            }
        });
        $('#add_image').tooltip();
    </script>
{% endblock %}

src/AppBundle/Resources/views/Work/Intervention/show.html.twig
{% extends 'AppBundle:Work/Intervention:layout.html.twig' %}

{% block title %}Intervention{% endblock %}

{% block content %}
    
    <div class="col-sm-7">
        <h2 class="sub-header">Intervention</h2>
        
        <div class="row">
            <div class="col-sm-8">
                <h4>Date intervention : {{ intervention.dateIntervention|date('d/m/Y') }}</h4>
                <h4>Intervenant : {{ intervention.createur.prenom ~ ' ' ~ intervention.createur.nom }}</h4>
                <h4>Notes : {{ intervention.notes }}</h4>
                <h4>Date et heure creation : {{ intervention.createdAt|date('d/m/Y H:i') }}</h4>
                <h4>Images</h4>
                {% if intervention.images.count > 0 %}
                <div class="row">
                    {% for image in intervention.images %}
                        <div class="col-sm-6">
                            <a class="thumbnail" href="{{ asset(image.webPath) }}" target="_blank">
                                <img src="{{ asset(image.webPath) }}">
                            </a>
                        </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
        
        <h3 class="sub-header"><a href="{{ path('interventions_index', { 'idOperation': intervention.operation.idOperation }) }}">Retour à la liste</a></h3>
    </div>
{% endblock %}